# Similar to roles/k3s/defaults/main.yml
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: homelab-dev
image: docker.io/rancher/k3s:v1.28.3-k3s2
servers: 1
agents: 0
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable-helm-controller
        nodeFilters:
          - server:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
