app-template:
  ingress:
    main:
      hosts:
        - host: &host budget.127-0-0-1.nip.io
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: actualbudget-tls-certificate
