argo-cd:
  global:
    domain: argocd.127-0-0-1.nip.io
argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL http://gitea-http.gitea:3000/ops/homelab
            revision: &revision dev-refactor
            directories:
              - path: system/*
              - path: platform/*
              - path: apps/*

              # TODO Cilium and Ceph doesn't work in dev sandbox yet
              - path: system/cilium
                exclude: true
              - path: system/rook-ceph
                exclude: true
      template:
        spec:
          source:
            repoURL: *repoURL
            targetRevision: *revision
            helm:
              valueFiles:
                - values-dev.yaml
